### ISSUE TITLE
Discordance in /exchange/spot/markets endpoint docs

### ISSUE THREAD

**Issue by paolodina** [stakecube/DevCube#3]
Hi, [accordingly to the docs](https://github.com/stakecube/DevCube/blob/master/rest-api/exchange.md#markets) the parameter `baseMarket` is required. (By mistake) I found that omitting it from the request the list of unfiltered results is returned.

As I'm currently using the `/exchange/spot/markets` endpoint without parameters, I wonder if it's allowed and if I can rely on this in the future.

**Comment by JSKitty** [comment]
Apologies for the documentation error, you are indeed allowed to use the `/exchange/spot/markets` endpoint without specifying a base market, I will fix this shortly! 😄

**Comment by JSKitty** [comment]
Resolved in https://github.com/stakecube/DevCube/commit/150e5da167fad7022052c9449dfe091fcc37a98d, closing, thank you!
